version: "3"
services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env.secret
    # command: python3 manage.py migrate --noinput
    command: python3 manage.py runserver 0.0.0.0:8000
    # command: sh -c "python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000 && python3 manage.py loaddata dump.json"
    # command: python3 manage.py loaddata dump.json
    entrypoint: ./docker-entrypoint.sh db 5432
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    # stdin_open: true
    # tty: true
    depends_on:
      - db
    # links:
    #   - db

  db:
    image: "postgres:10.3-alpine"
    restart: always
    env_file:
      - ./.env.secret
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
