# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-10 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20181110_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
