# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-10 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20181025_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='first_app.Category'),
            preserve_default=False,
        ),
    ]
